#!/bin/sh


yarn lint-staged

if [ $? -eq 0 ]; then
  echo ""
  echo "###################################################################################"
  echo "#                                                                                 #"
  echo "# 🐳 The commit completed successfully! Please push changes to the repository. 🐳 #"
  echo "#                                                                                 #"
  echo "###################################################################################"
  echo ""
fi

